### PR TITLE
Add redis

### PR DESCRIPTION
**Pull request by ryelo**

### CODE REVIEW

**Comment by ryelo** [comment]
@jharting This is ready for review

**Comment by jharting** [comment]
@ryelo shouldn't the cache also actually be used by the service? Or are you planning on introducing that in a separate PR?

**Comment by ryelo** [comment]
@jharting I was going to implement that in another PR, but I can add that to this if that would be easier.

**Review by jharting — APPROVED** [review]
@ryelo I am fine either way. Just curious. This looks good.

**Pull request merged**
